### PR TITLE
Set up semistandard linter #21

### PR DESCRIPTION
**Pull request by RQ16**
#21

### CODE REVIEW

**Comment by m4v15** [comment]
Description on the PR please

**Review by m4v15 — CHANGES_REQUESTED** [review]
Good stuff, just add a description please

**Comment by m4v15** [comment]
Also, did you not get a pre-commit warning because of the line router.js?

**Comment by m4v15** [comment]
What's going on with this now then?

**Comment by jwld** [comment]
Opening a new PR for this since we pushed some random stuff...

**Pull request closed without merging**
